### ISSUE TITLE
debug，然后反复运行初始阶段，同时LLMModel.completion()报错

### ISSUE THREAD

**Issue by ban-bu** [x-glacier/GenerativeAgentsCN#1]
非常感谢。但是似乎会出现debug，然后反复运行初始阶段。同时LLMModel.completion()也经常报错：LLMModel.completion() caused an error: 'choices'，想请教一下怎么解决谢谢
[[DEBUG]<20240213-09:30:00(on_time)>: 埃迪 add associate 这是 埃迪 在 2024年02月13日（星期二）09:30 的计划：早上 7 点起床；上午 10 点去奥克山学院上课；下午 5 点吃晚饭；下午 5 点后在霍布斯咖啡馆学习和吃饭；上午 10 点至下午 10 点继续在奥克山学院上课；晚上 7 点看电视或进行其他晚间活动 @ the Ville:林氏家族的房子:埃迪的卧室:床
[INFO]<20240213-09:30:00(on_time)>: 埃迪 -> schedule_decompose

**Comment by jiejieje** [comment]
看问题似乎是配置大语言模型（LLM）这个步骤没有搞好才导致的出错，LLMModel.completion() 'choices' 错误:是典型的 API 响应解析错误，一步一步按作者写的教程来吧，尤其是使用Ollama加载本地量化模型，如果不懂怎么配置可以点击蓝色字体的ollama.md进去查看详细步骤，如果是通过api接口调用大模型，就需要注意一下网络问题，有些可能需要翻墙才能使用

**Comment by ban-bu** [comment]
> 看问题似乎是配置大语言模型（LLM）这个步骤没有搞好才导致的出错，LLMModel.completion() 'choices' 错误:是典型的 API 响应解析错误，一步一步按作者写的教程来吧，尤其是使用Ollama加载本地量化模型，如果不懂怎么配置可以点击蓝色字体的ollama.md进去查看详细步骤，如果是通过api接口调用大模型，就需要注意一下网络问题，有些可能需要翻墙才能使用

谢谢，是尝试使用llama3.2模型替换原代码中的模型报错了。换成原来的，现在正常运行了
